env: "dev"
app:
  port: "7002"
  url: "https://iclaim.korkla.in"

pg:
  host: "ec2-107-22-101-0.compute-1.amazonaws.com"
  port: "5432"
  database: "df1a1e5v56qq2v"
  username: "kwhjoqffyawnwt"
  password: "1bdc4a4ac9cab04ac83fde2ec9bbf053a69122c232238c23cc03142f4d9f7a4b"

rg:
  host: "ec2-44-213-228-107.compute-1.amazonaws.com"
  port: "5432"
  database: "dali23acacvcqv"
  username: "gfzmupznfaenyu"
  password: "fd74fad513b5cb1c43abf706000c714aa2990e1db9dc0fadebf7f1bdebb4a4ba"

cache:
  host: "127.0.0.1"
  port: "6379"
  db: 3

notify:
  token: "1x9VoVXniwzPCfy8O058QBUTKLMXuC6T3MlQuTC9uwG"

jwt:
  member: "jXVra22bcVLZLKDDv6L4VVa&n%1JMHEXoEU33gNhcCu%fbHV2PZSlqXM2qkZ7U@"